name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phpstan:
    name: "Static analysis"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: |
          php vendor/bin/phpstan --version
          php vendor/bin/phpstan analyse -c phpstan.neon

  phpunit:
    name: "Unit tests"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3']
        symfony: [ '^5.0', '^6.0' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install symfony libs
        run: composer require symfony/mime:${{ matrix.symfony }} symfony/http-client:${{ matrix.symfony }} --with-all-dependencies

      - name: Run PHPUnit
        run: php vendor/bin/phpunit tests
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --diff --dry-run